# Generated by Django 5.0.6 on 2024-08-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoty', models.CharField(choices=[('GROCERIES', 'groceries'), ('LEISURE', 'leisure'), ('ELECTRONICS', 'electronics'), ('UTILITIES', 'utilities'), ('CLOTHING', 'clothing'), ('HEALTH', 'health'), ('OTHERS', 'others')], max_length=50)),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
