# Generated by Django 5.0.6 on 2024-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_app', '0004_alter_expense_categoty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categoty',
            field=models.CharField(choices=[('GROCERIES', 'groceries'), ('LEISURE', 'leisure'), ('ELECTRONICS', 'electronics'), ('UTILITIES', 'utilities'), ('CLOTHING', 'clothing'), ('HEALTH', 'health'), ('OTHERS', 'others')], default=('CLOTHING', 'clothing'), max_length=50),
        ),
    ]
