# Generated by Django 5.0.6 on 2024-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_app', '0005_alter_expense_categoty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='categoty',
        ),
        migrations.AddField(
            model_name='expense',
            name='categotry',
            field=models.CharField(choices=[('GROCERIES', 'groceries'), ('LEISURE', 'leisure'), ('ELECTRONICS', 'electronics'), ('UTILITIES', 'utilities'), ('CLOTHING', 'clothing'), ('HEALTH', 'health'), ('OTHERS', 'others')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
